# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/plasma-framework': '@latest-kf6'
    'frameworks/kwayland': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
